apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-app.fullname" . }}-service
spec:
  selector:
    app: {{ include "my-app.name" . }}
    environment: {{ .Values.environment }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
