name: Blue-Green Deployment-test
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}
    - name: Build and Push Docker Image
      run: |
        docker build -t ghcr.io/${{ github.repository }}:${{ github.sha }} .
        docker push ghcr.io/${{ github.repository }}:${{ github.sha }}
    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.10.0
    - name: Deploy to Minikube
      run: |
        minikube start
        helm upgrade --install my-app-blue ./my-app -f my-app/values.yaml --set image.tag=${{ github.sha }}
        # Deploy green environment
        helm upgrade --install my-app-green ./my-app -f my-app/values-green.yaml --set image.tag=${{ github.sha }}
        # Test green environment (add your test logic here)
        # Switch traffic to green
        kubectl patch service my-app-service -p '{"spec":{"selector":{"environment":"green"}}}'
