# my-app/values.yaml
replicaCount: 1
image:
  repository: ghcr.io/<your-username>/my-app
  tag: "2.0.0" # green version initially
environment: green
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: my-app.local
      paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: my-app-service
            servicePort: 80
